//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AttendenceManagementSystem1Entities : DbContext
    {
        public AttendenceManagementSystem1Entities()
            : base("name=AttendenceManagementSystem1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AcedemicYearMaster> AcedemicYearMasters { get; set; }
        public virtual DbSet<BranchMaster> BranchMasters { get; set; }
        public virtual DbSet<CollegeMaster> CollegeMasters { get; set; }
        public virtual DbSet<CountryMaster> CountryMasters { get; set; }
        public virtual DbSet<DeparmentMaster> DeparmentMasters { get; set; }
        public virtual DbSet<DistrictMaster> DistrictMasters { get; set; }
        public virtual DbSet<DivisionMaster> DivisionMasters { get; set; }
        public virtual DbSet<MonthMaster> MonthMasters { get; set; }
        public virtual DbSet<PeriodMaster> PeriodMasters { get; set; }
        public virtual DbSet<RoleMaster> RoleMasters { get; set; }
        public virtual DbSet<SectionMaster> SectionMasters { get; set; }
        public virtual DbSet<StandardMaster> StandardMasters { get; set; }
        public virtual DbSet<StateMaster> StateMasters { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<StudentAttendence> StudentAttendences { get; set; }
        public virtual DbSet<StudentAttendenceCount> StudentAttendenceCounts { get; set; }
        public virtual DbSet<SubjectMaster> SubjectMasters { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TeachersAttendence> TeachersAttendences { get; set; }
        public virtual DbSet<UserCredential> UserCredentials { get; set; }
        public virtual DbSet<UserDetailsMaster> UserDetailsMasters { get; set; }
        public virtual DbSet<YearMaster> YearMasters { get; set; }
    }
}
