//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollegeMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CollegeMaster()
        {
            this.BranchMasters = new HashSet<BranchMaster>();
            this.DeparmentMasters = new HashSet<DeparmentMaster>();
            this.PeriodMasters = new HashSet<PeriodMaster>();
            this.Students = new HashSet<Student>();
            this.StudentAttendences = new HashSet<StudentAttendence>();
            this.StudentAttendenceCounts = new HashSet<StudentAttendenceCount>();
            this.UserDetailsMasters = new HashSet<UserDetailsMaster>();
        }
    
        public int Id { get; set; }
        public string CollegeName { get; set; }
        public string Address { get; set; }
        public string Taluka { get; set; }
        public long DistrictId { get; set; }
        public int StateId { get; set; }
        public long PinCode { get; set; }
        public string ContactNo { get; set; }
        public string University { get; set; }
        public string Email { get; set; }
        public bool Status { get; set; }
        public Nullable<int> EntryBy { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<long> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string CollegeStartTime { get; set; }
        public string CollegeEndTime { get; set; }
        public Nullable<int> CountryId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BranchMaster> BranchMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeparmentMaster> DeparmentMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PeriodMaster> PeriodMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student> Students { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentAttendence> StudentAttendences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentAttendenceCount> StudentAttendenceCounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserDetailsMaster> UserDetailsMasters { get; set; }
    }
}
