//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PeriodMaster
    {
        public int Id { get; set; }
        public int CollegeId { get; set; }
        public int DepartmentId { get; set; }
        public int SectionId { get; set; }
        public long Period { get; set; }
        public Nullable<bool> Session { get; set; }
        public string Sessions { get; set; }
        public string TimeFrom { get; set; }
        public string TimeTo { get; set; }
        public Nullable<int> EntryBy { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual CollegeMaster CollegeMaster { get; set; }
        public virtual DeparmentMaster DeparmentMaster { get; set; }
        public virtual DeparmentMaster DeparmentMaster1 { get; set; }
        public virtual SectionMaster SectionMaster { get; set; }
    }
}
