//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.StudentAttendences = new HashSet<StudentAttendence>();
            this.StudentAttendenceCounts = new HashSet<StudentAttendenceCount>();
        }
    
        public int Id { get; set; }
        public Nullable<long> URNNo { get; set; }
        public Nullable<long> RollNo { get; set; }
        public Nullable<int> CollegeId { get; set; }
        public Nullable<int> SectionId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> AcademicYearId { get; set; }
        public Nullable<bool> Gender { get; set; }
        public string AadharNo { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string GrandFatherName { get; set; }
        public string MotherName { get; set; }
        public string ContactNo { get; set; }
        public string EmailId { get; set; }
        public string Religion { get; set; }
        public string Caste { get; set; }
        public string Nationality { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Village { get; set; }
        public string Taluka { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<long> Pincode { get; set; }
        public Nullable<int> StandardId { get; set; }
        public Nullable<int> DivisionId { get; set; }
        public Nullable<int> YearId { get; set; }
        public Nullable<int> EntryBy { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string Photo { get; set; }
        public Nullable<int> Flag { get; set; }
        public int BranchId { get; set; }
    
        public virtual AcedemicYearMaster AcedemicYearMaster { get; set; }
        public virtual BranchMaster BranchMaster { get; set; }
        public virtual CollegeMaster CollegeMaster { get; set; }
        public virtual CountryMaster CountryMaster { get; set; }
        public virtual DeparmentMaster DeparmentMaster { get; set; }
        public virtual DistrictMaster DistrictMaster { get; set; }
        public virtual DivisionMaster DivisionMaster { get; set; }
        public virtual SectionMaster SectionMaster { get; set; }
        public virtual YearMaster YearMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentAttendence> StudentAttendences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentAttendenceCount> StudentAttendenceCounts { get; set; }
    }
}
