//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentAttendence
    {
        public int Id { get; set; }
        public int CollegeID { get; set; }
        public int StudentID { get; set; }
        public int SubjectId { get; set; }
        public int StandardID { get; set; }
        public int DivisionID { get; set; }
        public Nullable<int> EntryBy { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<bool> Flag { get; set; }
        public Nullable<int> Status { get; set; }
        public string Remark { get; set; }
    
        public virtual CollegeMaster CollegeMaster { get; set; }
        public virtual DivisionMaster DivisionMaster { get; set; }
        public virtual StandardMaster StandardMaster { get; set; }
        public virtual Student Student { get; set; }
        public virtual SubjectMaster SubjectMaster { get; set; }
    }
}
