//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCredential
    {
        public int Id { get; set; }
        public Nullable<int> RoleID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<bool> Flag { get; set; }
        public Nullable<bool> EmailFlag { get; set; }
        public Nullable<System.DateTime> EmailSentOn { get; set; }
        public string IP_ADDRESS { get; set; }
        public Nullable<System.DateTime> LAST_lOGIN { get; set; }
        public Nullable<System.DateTime> CurrentLogin_time { get; set; }
        public string JsonResponse { get; set; }
    
        public virtual RoleMaster RoleMaster { get; set; }
        public virtual UserDetailsMaster UserDetailsMaster { get; set; }
    }
}
